# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: Yas3r

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Yas3r

description: Stylish Jekyll Theme
author:
  name: Yas3r
  email: dbyll@ismaildemirbilek.com
  github: Yas3r
  twitter: yaserfaraj
  pinterest: 
  linkedin: yaserfaraj
  bio: Ph.D. in Computer Science / Network Security 
  email_md5: 726351295ec82e145928582f595aa3aa
  hackthbox: https://www.hackthebox.eu/badge/596
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
permalink: /:categories/:title

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
